server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billycard?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    username: sqluser
    password: password
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: update

management:
  endpoints:
    enabled-by-default: true